name:                in-silico
version:             0.1.0.0
github:              "githubuser/in-silico"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/in-silico#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- containers
- safe
- QuickCheck


default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveGeneric
- DeriveLift
- DeriveTraversable           # Implies: DeriveFoldable, DeriveFunctor
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances           # Implies: TypeSynonymInstances
- FunctionalDependencies      # Implies: MultiParamTypeClasses
- GADTs                       # Implies: GADTSyntax, MonoLocalBinds
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MagicHash
- MultiParamTypeClasses       # Implies: ConstrainedClassMethods
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- NoStarIsType
- NumericUnderscores
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- RankNTypes                  # Implies: ExplicitForAll
- RecordWildCards             # Implies: DisambiguateRecordFields
- ScopedTypeVariables         # Implies: ExplicitForAll
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilyDependencies      # Implies: TypeFamilies
- TypeInType                  # Implies: DataKinds, KindSignatures, PolyKinds
- TypeOperators               # Implies: ExplicitNamespaces
- ViewPatterns

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-unticked-promoted-constructors
  - -Wsemigroup
  - -Wmissing-monadfail-instances
  - -Wnoncanonical-monoid-instances
  - -Wnoncanonical-monad-instances
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wimplicit-prelude
  - -Wmissing-home-modules
  - -Werror

executables:
  in-silico-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unticked-promoted-constructors
    - -Wsemigroup
    - -Wmissing-monadfail-instances
    - -Wnoncanonical-monoid-instances
    - -Wnoncanonical-monad-instances
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wimplicit-prelude
    - -Wmissing-home-modules
    - -Werror
    dependencies:
    - in-silico

tests:
  in-silico-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - in-silico
    - hspec
